basicapp/urls.py
from django.urls import path
from basicapp import views

 #TEMPLATE TAGGING
app_name = 'basicapp'
urlpatterns =[
     path(r'relative/',views.relative,name='relative'),
     path(r'other/',views.other,name='other'),
 ]

temppro/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views


urlpatterns = [
    path(r'home',views.index,name='index'),
    path('admin/', admin.site.urls),
    path(r'basic/',include('basicapp.urls'))
]

basicapp/models.py
from django.db import models

# Create your models here.

basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	context_dict = {'text':'hello world','number':100}
	return render(request,'basicapp/index.html',context_dict)

def other(request):
	return render(request,'basicapp/other.html')

def relative(request):
	return render(request,'basicapp/relative_url_templates.html')

templates/basicapp/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title> </title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			<ul class="nav navbar-nav">
				<li><a class="navbar-brand" href="{% url 'index' %}">BRAND<a></li>
				<li><a class="navbar-link" href="{% url 'admin:index' %}">Admin<a></li>
                <li><a class="navbar-link" href="{% url 'basicapp:other' %}">Other<a></li>
            </ul>
		</div> 
		
	</nav>
	<div class="container">
		{% block body_block %}
		<!-- Anything outside of this will be inherited if you extend -->
		{% endblock %}

</body>
</html>

templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body_block %}
   <h1>welcome to index!</h1>
   <h2> Hello  </h2>
   <!-- <h2>This is index.html page showing!</h2> -->
   <h1>{{ text|cut:'hello' }}</h1>
   <h1>{{ number|add:"99" }}</h1>
{% endblock %}
	
  

templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}
<h1>welcome to other!</h1>
<h2>Templates inheritance!</h2>
{% endblock %}

templates/basicapp/relative_url_templates.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <!-- <a href="basicapp/other.html">THE OTHER PAGE</a> -->
    <a href="{% url 'basicapp:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
    <a href="{% url 'index' %}">LINK TO INDEX</a>
    
</body>
</html>